### ISSUE TITLE
The pickle file cannot be loaded

### ISSUE THREAD

**Issue by chunchet** [leezhiqiangleonard/IMDA_offline_test#1]
The error message as follows.

`>>> import pickle
>>> preprocessing_d = pickle.load(open('preprocessing_d.pkl', 'rb'))
/Users/eric/playground/The-CAPTCHA-Cracker/answers/IMDA_offline_test/.env/lib/python3.10/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator LabelEncoder from version 1.0.2 when using version 1.1.3. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
2022-11-30 14:00:40.220093: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/eric/playground/The-CAPTCHA-Cracker/answers/IMDA_offline_test/.env/lib/python3.10/site-packages/keras/saving/pickle_utils.py", line 48, in deserialize_model_from_bytecode
    raise e
  File "/Users/eric/playground/The-CAPTCHA-Cracker/answers/IMDA_offline_test/.env/lib/python3.10/site-packages/keras/saving/pickle_utils.py", line 46, in deserialize_model_from_bytecode
    model = saving_lib.load_model(filepath)
  File "/Users/eric/playground/The-CAPTCHA-Cracker/answers/IMDA_offline_test/.env/lib/python3.10/site-packages/keras/saving/experimental/saving_lib.py", line 196, in load_model
    raise e
  File "/Users/eric/playground/The-CAPTCHA-Cracker/answers/IMDA_offline_test/.env/lib/python3.10/site-packages/keras/saving/experimental/saving_lib.py", line 173, in load_model
    with zipfile.ZipFile(filepath, "r") as zipfile_to_load:
  File "/usr/local/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/zipfile.py", line 1267, in __init__
    self._RealGetContents()
  File "/usr/local/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/zipfile.py", line 1334, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file`

**Comment by leezhiqiangleonard** [comment]
I believe it is cause of different versions of pickle. I will update with a requirements text file. @chunchet

**Comment by leezhiqiangleonard** [comment]
> The error message as follows.
> 
> `>>> import pickle
> 
> > > > preprocessing_d = pickle.load(open('preprocessing_d.pkl', 'rb'))
> > > > /Users/eric/playground/The-CAPTCHA-Cracker/answers/IMDA_offline_test/.env/lib/python3.10/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator LabelEncoder from version 1.0.2 when using version 1.1.3. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
> > > > https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
> > > > warnings.warn(
> > > > 2022-11-30 14:00:40.220093: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
> > > > To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > File "/Users/eric/playground/The-CAPTCHA-Cracker/answers/IMDA_offline_test/.env/lib/python3.10/site-packages/keras/saving/pickle_utils.py", line 48, in deserialize_model_from_bytecode
> > > > raise e
> > > > File "/Users/eric/playground/The-CAPTCHA-Cracker/answers/IMDA_offline_test/.env/lib/python3.10/site-packages/keras/saving/pickle_utils.py", line 46, in deserialize_model_from_bytecode
> > > > model = saving_lib.load_model(filepath)
> > > > File "/Users/eric/playground/The-CAPTCHA-Cracker/answers/IMDA_offline_test/.env/lib/python3.10/site-packages/keras/saving/experimental/saving_lib.py", line 196, in load_model
> > > > raise e
> > > > File "/Users/eric/playground/The-CAPTCHA-Cracker/answers/IMDA_offline_test/.env/lib/python3.10/site-packages/keras/saving/experimental/saving_lib.py", line 173, in load_model
> > > > with zipfile.ZipFile(filepath, "r") as zipfile_to_load:
> > > > File "/usr/local/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/zipfile.py", line 1267, in **init**
> > > > self._RealGetContents()
> > > > File "/usr/local/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/zipfile.py", line 1334, in _RealGetContents
> > > > raise BadZipFile("File is not a zip file")
> > > > zipfile.BadZipFile: File is not a zip file`

I have added the requirements.txt file and instructions as to how to use it in the README.md file along with the python version requirements. @chunchet
